src/MyBlog.Web/Areas/Admin/Controllers/BaseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MyBlog.Web.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize]
    public abstract class BaseController : Controller
    {
    }
}

src/MyBlog.Web/Controllers/PostsController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MyBlog.Core.Queries;
using MyBlog.Web.Models;
using System;
using System.Net;
using System.Threading.Tasks;

namespace MyBlog.Web.Controllers
{
    public class PostsController : Controller
    {
        private readonly IMediator _mediator;
        private readonly AppSettings _appSettings;

        public PostsController(IMediator mediator, IOptions<AppSettings> settings)
        {
            _mediator = mediator;
            _appSettings = settings.Value;
        }

        // GET: Post/PostDetail
        [Route("post/{year}/{month}/{day}/{slug}")]
        public async Task<ActionResult> PostDetail(int year, int month, int day, string slug)
        {
            var result = DateTime.TryParse($"{month}/{day}/{year} 00:00:00", out var date);
            if (!result)
                return NotFound();

            var post = await _mediator.Send(new PostGetActiveBySlugAndDateQuery(date, slug));
            if (post == null)
                return NotFound();

            return View(post);
        }

        // GET: Post/PostDetail
        [Route("post/{id}/{slug}")]
        public async Task<ActionResult> PostDetail(string id, string slug)
        {
            if (_appSettings.Redirect.ContainsKey(id))
            {
                var parts = _appSettings.Redirect[id].Split('/');
                return RedirectPermanent(Url.Action("PostDetail", new { year = parts[0], month = parts[1], day = parts[2], slug = parts[3] }));
            }

            var post = await _mediator.Send(new PostGetOldBySlugQuery(slug));
            if (post == null)
                return NotFound();

            return RedirectPermanent(
                Url.Action("PostDetail", new { post.CreateDate.Year, post.CreateDate.Month, post.CreateDate.Day, post.Slug }));
        }

        // GET: Post/PostsByTag
        [Route("tag/{slug}")]
        public async Task<ActionResult> PostsByTag(string slug, int page = 1)
        {
            if (string.IsNullOrEmpty(slug))
                return new StatusCodeResult((int)HttpStatusCode.BadRequest);

            var (posts, postCount) = await _mediator.Send(new PostGetsPagedQuery(page, slug));
            var homeViewModel = new HomeViewModel
            {
                CurrentPage = page,
                Posts = posts,
                TotalPosts = postCount
            };

            return View("~/Views/Home/Index.cshtml", homeViewModel);
        }
    }
}

src/MyBlog.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyBlog</title>

    <environment include="Development">
        <link href="~/css/bootstrap.css" rel="stylesheet" />
        <link href="~/css/adminlte.css" rel="stylesheet" />
        <link href="~/lib/fontawesome/css/font-awesome.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/admin.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("header", false)
</head>
<body class="skin-black" dir="rtl">
    <header class="header">
        <a href="/" class="logo" target="_blank">
            <!-- Add the class icon to your logo image or logo icon to add the margining -->
            MyBlog
        </a>

        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="navbar-right">
                <ul class="nav navbar-nav">
                    <!-- Messages: style can be found in dropdown.less-->
                    <li class="dropdown messages-menu">
                        @*@{Html.RenderAction("NewMessage", "Base");}*@
                    </li>

                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span><i class="fa fa-user"></i> ادمین </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-footer">
                                <div class="pull-right">
                                    <a asp-area="" asp-controller="Account" asp-action="ChangePassword" class="btn btn-default btn-flat">
                                        <i class="fa fa-lock"></i>
                                        تغییر رمز عبور
                                    </a>
                                </div>
                                <div class="pull-left">
                                    <a asp-area="" asp-controller="Account" asp-action="Logout" class="btn btn-default btn-flat">
                                        <i class="fa fa-sign-out"></i>
                                        خروج
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="wrapper row-offcanvas row-offcanvas-right">
        <aside class="right-side sidebar-offcanvas">
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-right info">
                        <p>خوش آمدید</p>
                    </div>
                </div>

                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li>
                        <a asp-controller="Home" asp-action="Index">
                            <i class="fa fa-home"></i> <span>صفحه اصلی</span>
                        </a>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-newspaper-o"></i>
                            <span>مقاله</span>
                            <i class="fa fa-angle-right pull-left"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a asp-controller="Posts" asp-action="Create"><i class="fa fa-angle-double-left"></i> افزودن مقاله</a></li>
                            <li><a asp-controller="Posts" asp-action="Index"><i class="fa fa-angle-double-left"></i> لیست مقاله ها</a></li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-tag"></i>
                            <span>تگ</span>
                            <i class="fa fa-angle-right pull-left"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a asp-controller="Tags" asp-action="Create"><i class="fa fa-angle-double-left"></i> افزودن تگ</a></li>
                            <li><a asp-controller="Tags" asp-action="Index"><i class="fa fa-angle-double-left"></i> لیست تگها</a></li>
                        </ul>
                    </li>
                    <li> <a asp-controller="Messages" asp-action="Index"><i class="fa fa-comment-o"></i> پیامها</a> </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <aside class="left-side">
            <section class="content-header">
                @RenderSection("ContentHeader", false)
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <!-- Small boxes (Stat box) -->
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </section>
        </aside>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery.slimscroll/jquery.slimscroll.js"></script>
        <script src="~/lib/jquery-icheck/icheck.js"></script>
        <script src="~/lib/jquery-autosize/dist/autosize.min.js"></script>
        <script src="~/js/helper.js"></script>
        <script src="~/js/startup.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/admin.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>