src/MyBlog.Web/Models/HomeViewModel.cs
using MyBlog.Core.Entities;
using System.Collections.Generic;

namespace MyBlog.Web.Models
{
    public class HomeViewModel
    {
        public int CurrentPage { get; set; }

        public int TotalPage => TotalPosts % 5 != 0 ? TotalPosts / 5 + 1 : TotalPosts / 5;

        public int TotalPosts { get; set; }

        public IEnumerable<PostEntity> Posts { get; set; }
    }
}

src/MyBlog.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.IO;
using System.Threading.Tasks;

namespace MyBlog.Web.Areas.Admin.Controllers
{
    public class HomeController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> UploadImage([FromServices]IConfiguration configuration, [FromServices] IHostingEnvironment environment,
            IFormFile upload, string CKEditorFuncNum, string CKEditor, string langCode)
        {
            if (upload == null || upload.Length <= 0)
                return null;

            var uploadFolder = configuration["AppSettings:ImageUploadPath"];

            var path = Path.Combine(environment.WebRootPath, uploadFolder, upload.FileName);
            using (var outputFile = System.IO.File.OpenWrite(path))
            {
                await upload.OpenReadStream().CopyToAsync(outputFile);
                outputFile.Close();
            }

            var request = HttpContext.Request;
            var imageVirtualPath = Path.Combine(uploadFolder, upload.FileName);
            var uriBuilder = new UriBuilder
            {
                Host = request.Host.Host,
                Scheme = request.Scheme,
                Path = imageVirtualPath
            };

            if (request.Host.Port.HasValue)
                uriBuilder.Port = request.Host.Port.Value;

            var url = uriBuilder.ToString();

            const string message = "عکس با موفقیت آپلود شد.";

            var output = $"<html><body><script>window.parent.CKEDITOR.tools.callFunction({CKEditorFuncNum}, \"{url}\", \"{message}\");</script></body></html>";

            return Content(output, "text/html");
        }
    }
}

src/MyBlog.Web/Controllers/HomeController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Core.Queries;
using MyBlog.Web.Models;
using System;
using System.Diagnostics;
using System.Threading.Tasks;

namespace MyBlog.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IMediator _mediator;

        public HomeController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [Route("page/{page?}")]
        [Route("/")]
        public async Task<IActionResult> Index(int page = 1)
        {
            var (posts, postCount) = await _mediator.Send(new PostGetsPagedQuery(page));
            var homeViewModel = new HomeViewModel
            {
                CurrentPage = page,
                Posts = posts,
                TotalPosts = postCount
            };

            return View("~/Views/Home/Index.cshtml", homeViewModel);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Contact(ContactMessageViewModel viewModel)
        //{
        //    if (!ModelState.IsValid)
        //        return View(viewModel);

        //    var message = Mapper.Map<ContactMessageEntity>(viewModel);
        //    await _mediator.Send(new MessageAddCommand(message));

        //    if (!await _unitOfWork.CommitAsync())
        //    {
        //        ModelState.AddModelError("Create", "هنگام ثبت پیام خطایی رخ داده است. لطفا بعدا سعی نمایید.");
        //        return View(viewModel);
        //    }

        //    await _mailService.Value.ContactMail(contactMessage.Name, contactMessage.Email, contactMessage.Message).SendAsync();
        //    TempData["Successful"] = true;
        //    ModelState.Clear();

        //    return View();
        //}

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/MyBlog.Web/Controllers/PostsController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using MyBlog.Core.Queries;
using MyBlog.Web.Models;
using System;
using System.Net;
using System.Threading.Tasks;

namespace MyBlog.Web.Controllers
{
    public class PostsController : Controller
    {
        private readonly IMediator _mediator;
        private readonly AppSettings _appSettings;

        public PostsController(IMediator mediator, IOptions<AppSettings> settings)
        {
            _mediator = mediator;
            _appSettings = settings.Value;
        }

        // GET: Post/PostDetail
        [Route("post/{year}/{month}/{day}/{slug}")]
        public async Task<ActionResult> PostDetail(int year, int month, int day, string slug)
        {
            var result = DateTime.TryParse($"{month}/{day}/{year} 00:00:00", out var date);
            if (!result)
                return NotFound();

            var post = await _mediator.Send(new PostGetActiveBySlugAndDateQuery(date, slug));
            if (post == null)
                return NotFound();

            return View(post);
        }

        // GET: Post/PostDetail
        [Route("post/{id}/{slug}")]
        public async Task<ActionResult> PostDetail(string id, string slug)
        {
            if (_appSettings.Redirect.ContainsKey(id))
            {
                var parts = _appSettings.Redirect[id].Split('/');
                return RedirectPermanent(Url.Action("PostDetail", new { year = parts[0], month = parts[1], day = parts[2], slug = parts[3] }));
            }

            var post = await _mediator.Send(new PostGetOldBySlugQuery(slug));
            if (post == null)
                return NotFound();

            return RedirectPermanent(
                Url.Action("PostDetail", new { post.CreateDate.Year, post.CreateDate.Month, post.CreateDate.Day, post.Slug }));
        }

        // GET: Post/PostsByTag
        [Route("tag/{slug}")]
        public async Task<ActionResult> PostsByTag(string slug, int page = 1)
        {
            if (string.IsNullOrEmpty(slug))
                return new StatusCodeResult((int)HttpStatusCode.BadRequest);

            var (posts, postCount) = await _mediator.Send(new PostGetsPagedQuery(page, slug));
            var homeViewModel = new HomeViewModel
            {
                CurrentPage = page,
                Posts = posts,
                TotalPosts = postCount
            };

            return View("~/Views/Home/Index.cshtml", homeViewModel);
        }
    }
}

src/MyBlog.Web/ViewComponents/TagsViewComponent.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Core.Queries;
using System.Threading.Tasks;

namespace MyBlog.Web.ViewComponents
{
    public class TagsViewComponent : ViewComponent
    {
        private readonly IMediator _mediator;

        public TagsViewComponent(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var tags = await _mediator.Send(new TagGetsQuery());

            return View(tags);
        }
    }
}

src/MyBlog.Web/Views/Home/About.cshtml
@section header{
    <meta name="keyword" content="محسن اسماعیل پور, Mohsen Esmailpour, بلاگ من, .net, c#, asp.net mvc, asp.net core, entity framework, entity framework core, javascript, jquery, web api" />
    <meta name="description" content="I'm newbie software developer with a particular interest in web technologies and creating web application with Microsoft technologies." />
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />
}

@{
    ViewData["Title"] = "درباره";
}

<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1" style="text-align: center">
    <p>هر چی فکر کردم چیزی به ذهنم نرسید که بنویسیم. شاید در آینده بیشتر فکر کردم !</p>
    <div class="social">
        <div class="menu-item">
            <span class="icon fa fa-twitter"></span>
            <a target="_blank" class="text" href="https://twitter.com/moesmp">
                <i class="fa fa-twitter"></i>
            </a>
        </div>
        @*<div class="menu-item">
                <span class="icon fa fa-linkedin"></span>
                <a target="_blank" class="text" href="http://ir.linkedin.com/pub/mohsen-esmailpour/51/38b/827">
                    <i class="fa fa-linkedin"></i>
                </a>
            </div>*@
        <div class="menu-item">
            <span class="icon fa fa-stack-overflow"></span>
            <a target="_blank" class="text" href="http://stackoverflow.com/users/1385614/mo-esmp">
                <i class="fa fa-stack-overflow"></i>
            </a>
        </div>
        <div class="menu-item">
            <span class="icon fa fa-github"></span>
            <a target="_blank" class="text" href="https://github.com/mo-esmp">
                <i class="fa fa-github"></i>
            </a>
        </div>
    </div>
</div>
@section scripts {
    <script>
        $(function () {
            $('.menu-item').hover(function () {
                $('.icon', this).toggleClass('active');
                $('.icon', this).css({ 'display': 'block' }); //adds context
            });
        });
    </script>
}

src/MyBlog.Web/Views/Home/Contact.cshtml
@model ContactMessageViewModel

@section header{
    <meta name="keyword" content="محسن اسماعیل پور, Mohsen Esmailpour, بلاگ من, .net, c#, asp.net mvc, asp.net core, entity framework, entity framework core, javascript, jquery, web api" />
    <meta name="description" content="I'm newbie software developer with a particular interest in web technologies and creating web application with Microsoft technologies." />
}

@{
    ViewData["Title"] = "تماس";
}

<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <p><i class="fa fa-send-o"></i> برای ارتباط با من از پست الکترونیک زیر استفاده نمایید.</p>
    <p><i class="fa fa-envelope-o"></i> mo [dot] esmp [at] gmail [dot] com</p>

    @*@if (!ViewData.ModelState.IsValid)
        {
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            @Html.ValidationSummary()
        </div>
        }

        @if (TempData["Successful"] != null)
        {
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <strong>با تشکر پیام شما با موفقیت ثبت شد.</strong>
        </div>
        }*@

    @*<form asp-action="Contact" method="post" role="form">
            @Html.AntiForgeryToken()
            <div class="row control-group">
                <div class="form-group col-xs-8 floating-label-form-group controls">
                    <label asp-for="Name"></label>
                    @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control type-directio", placeholder = "نام" } })
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="row control-group">
                <div class="form-group col-xs-8 floating-label-form-group controls">
                    @Html.LabelFor(m => m.Email)
                    @Html.EditorFor(m => m.Email, new { htmlAttributes = new { @class = "form-control left-text", placeholder = "ایمیل" } })
                    @Html.ValidationMessageFor(m => m.Email, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="row control-group">
                <div class="form-group col-xs-12 floating-label-form-group controls">
                    @Html.LabelFor(m => m.Message)
                    @Html.EditorFor(m => m.Message, new { htmlAttributes = new { @class = "form-control type-direction", placeholder = "پیام" } })
                    @Html.ValidationMessageFor(m => m.Message, null, new { @class = "text-danger" })
                </div>
            </div>
            <br>
            <div class="row">
                <div class="form-group col-xs-12">
                    <button type="submit" class="btn btn-default pull-left">ارسال</button>
                </div>
            </div>
        </form>*@
</div>

@*@section scripts {
            {await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/lib/jquery-autosize/dist/autosize.js"></script>
    <script>
        autosize(document.querySelector('textarea'));
    </script>
    }*@

src/MyBlog.Web/Views/Home/Index.cshtml
@using MyBlog.Infrastructure.Extensions
@model HomeViewModel

@section header{
    <meta name="keyword" content="محسن اسماعیل پور, Mohsen Esmailpour, بلاگ من, .net, c#, asp.net mvc, asp.net core, entity framework, entity framework core, javascript, jquery, web api" />
    <meta name="description" content="I'm newbie software developer with a particular interest in web technologies and creating web application with Microsoft technologies." />
}

@{
    ViewData["Title"] = "صفحه اصلی";
}

<vc:tags></vc:tags>

<div class="col-lg-8 col-lg-offset-0 col-md-9 col-md-offset-0">
    @foreach (var post in Model?.Posts)
    {
        <div class="post-preview">
            <a asp-controller="Posts" asp-action="PostDetail" asp-route-year="@post.CreateDate.Year" asp-route-month="@post.CreateDate.Month" asp-route-day="@post.CreateDate.Day" asp-route-slug="@post.Slug">
                <h2 class="post-title">
                    @post.Title
                </h2>
                <div class="post-subtitle">
                    @Html.Raw(post.Content.TruncateHtml(350, "..."))
                </div>
            </a>
            <p class="post-meta">
                <a><i class="glyphicon glyphicon-calendar"></i></a>&nbsp;<span class="date">@post.CreateDate.ToJalaliDateTimeFullString().ToPersianDigits()</span> <span class="divider-vertical"></span>
                <a><i class="glyphicon glyphicon-comment"></i></a>&nbsp;&nbsp;<span class="disqus-comment-count" data-disqus-identifier="@post.Id"></span> <span class="divider-vertical"></span>
                <a> <i class="glyphicon glyphicon-tag"></i></a>&nbsp;
                <span>
                    @foreach (var tag in post.PostTags.Select(pt => pt.Tag))
                    {
                        <a asp-action="PostsByTag" asp-controller="Posts" asp-route-slug="@tag.Slug">@tag.Name</a>
                        <text>&nbsp;</text>
                    }
                </span>
            </p>
        </div>
        <hr />
    }

    <!-- Pager -->
    @if (Model?.TotalPosts > 5)
    {
        <ul class="pager">
            @if (Model.CurrentPage != 1)
            {
                var next = Model.CurrentPage - 1;
                <li class="next">
                    <a asp-action="Index" asp-route-page="@next">پست های جدیدتر &larr;</a>
                </li>
            }
            @if (Model.CurrentPage != Model.TotalPage)
            {
                var prev = Model.CurrentPage + 1;
                <li class="previous">
                    <a asp-action="Index" asp-route-page="@prev">پست های قدیمی تر &rarr;</a>
                </li>
            }
        </ul>
    }
</div>

@section Scripts {
    <script id="dsq-count-scr" src="//mohsenes.disqus.com/count.js" async></script>
}